### ISSUE TITLE
City in 253/071/413 looks wrong

### ISSUE THREAD

**Issue by nigelhorne** [whosonfirst-data/whosonfirst-data-venue-au#1]
"sg:city":"Caroline Springs Blv Caroline Springs"

I suspect that should read

    "sg:city":"Caroline Springs"

There are other records in that file which seem suspect.

**Comment by thisisaaronland** [comment]
The `sg:` attributes should be considered historic and non-authoritative. As a rule we tend to preserve source attributes (in this case SimpleGeo) as-is. The hierarchy for that record correctly lists "Caroline Springs" as the locality:

https://spelunker.whosonfirst.org/id/101932727/

A corollary to this is the long-standing "TO DO" item to add a fully qualified `wof:label` attribute to all records, separate and distinct from `wof:name`, which would include things like city and region. It's on the list...

**Comment by nigelhorne** [comment]
@Thanks for your reply.  That makes sense, except that I can't see which field contains the city's name.  I'm sure it's documented somewhere that I haven't found yet, could you give me a gentle nudge in the right direction, please?

Neither hierachy->region_id not wof:parent_id help:

sqlite> select * from  geojson where id = 85681497;
sqlite> select * from  geojson where id = 85776613;

**Comment by nigelhorne** [comment]
I also tried the id you gave, but nothing came back:

select * from  geojson where id = 101932727;
